### ISSUE TITLE
QuarksJS: "Create up to" box doesn't validate

### ISSUE THREAD

**Issue by tomtheisen** [ChrisTheisen/christheisen.github.io#2]
I guess you can just type a really big number, and it won't be questioned.

![image](https://github.com/ChrisTheisen/christheisen.github.io/assets/2049910/d95221b3-7a1e-4298-9cef-abea0ac3a650)

Witness how I'm creating like a billion quarks.

**Comment by ChrisTheisen** [comment]
Resolved with recent update.
